import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SecondWindow(object):
    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.resize(1122, 894)
        self.centralwidget = QtWidgets.QWidget(SecondWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ArkaPlan = QtWidgets.QLabel(self.centralwidget)
        self.ArkaPlan.setGeometry(QtCore.QRect(0, -10, 1131, 961))
        self.ArkaPlan.setPixmap(QtGui.QPixmap("ArkaPlan.jpg"))
        self.ArkaPlan.setText("")
        self.ArkaPlan.setObjectName("ArkaPlan")
        self.satisyap = QtWidgets.QPushButton(self.centralwidget)
        self.satisyap.setGeometry(QtCore.QRect(420, 740, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.satisyap.setFont(font)
        self.satisyap.setStyleSheet("background-color: rgb(57, 57, 57);\n"
"color: rgb(96, 255, 10);\n"
"border-radius:25px;")
        self.satisyap.setObjectName("satisyap")
        self.Telif = QtWidgets.QLabel(self.centralwidget)
        self.Telif.setGeometry(QtCore.QRect(410, 830, 341, 20))
        self.Telif.setObjectName("Telif")
        self.barkodbilgi = QtWidgets.QLabel(self.centralwidget)
        self.barkodbilgi.setGeometry(QtCore.QRect(270, 200, 421, 41))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.barkodbilgi.setFont(font)
        self.barkodbilgi.setObjectName("barkodbilgi")
        self.barkodgiris = QtWidgets.QLineEdit(self.centralwidget)
        self.barkodgiris.setGeometry(QtCore.QRect(270, 240, 601, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.barkodgiris.setFont(font)
        self.barkodgiris.setStyleSheet("color: rgb(51, 208, 16);\n"
"\n"
"")
        self.barkodgiris.setText("")
        self.barkodgiris.setObjectName("barkodgiris")
        self.urunadibilgi = QtWidgets.QLabel(self.centralwidget)
        self.urunadibilgi.setGeometry(QtCore.QRect(270, 390, 421, 31))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.urunadibilgi.setFont(font)
        self.urunadibilgi.setObjectName("urunadibilgi")
        self.urunadigirs = QtWidgets.QLineEdit(self.centralwidget)
        self.urunadigirs.setGeometry(QtCore.QRect(270, 420, 601, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.urunadigirs.setFont(font)
        self.urunadigirs.setStyleSheet("color: rgb(51, 208, 16);\n"
"\n"
"")
        self.urunadigirs.setText("")
        self.urunadigirs.setObjectName("urunadigirs")
        self.urunfiyatibilgi = QtWidgets.QLabel(self.centralwidget)
        self.urunfiyatibilgi.setGeometry(QtCore.QRect(270, 560, 421, 31))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.urunfiyatibilgi.setFont(font)
        self.urunfiyatibilgi.setObjectName("urunfiyatibilgi")
        self.urunfiyatigiris = QtWidgets.QLineEdit(self.centralwidget)
        self.urunfiyatigiris.setGeometry(QtCore.QRect(270, 590, 601, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.urunfiyatigiris.setFont(font)
        self.urunfiyatigiris.setStyleSheet("color: rgb(51, 208, 16);\n"
"\n"
"")
        self.urunfiyatigiris.setText("")
        self.urunfiyatigiris.setObjectName("urunfiyatigiris")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(470, 20, 211, 151))
        self.logo.setPixmap(QtGui.QPixmap("denemee2.png"))
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.bilgilendirme = QtWidgets.QLabel(self.centralwidget)
        self.bilgilendirme.setGeometry(QtCore.QRect(360, 670, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bilgilendirme.setFont(font)
        self.bilgilendirme.setText("")
        self.bilgilendirme.setObjectName("bilgilendirme")
        SecondWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SecondWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1122, 21))
        self.menubar.setObjectName("menubar")
        SecondWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SecondWindow)
        self.statusbar.setObjectName("statusbar")
        SecondWindow.setStatusBar(self.statusbar)
        self.satisyap.clicked.connect(self.bilgial)
        self.retranslateUi(SecondWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)

    def bilgial(self):
        tablo = sqlite3.Connection("ürünler.db")
        edit = tablo.cursor()
        isim = self.urunadigirs.text()
        barkod = self.barkodgiris.text()
        fiyat = self.urunfiyatigiris.text()
        if (len(isim) == 0 or len(fiyat) == 0 or len(barkod) == 0):
            self.bilgilendirme.setText("!!LÜTFEN BİLGİLERİ EKSİKSİZ GİRİN!!")
        else:
            self.bilgilendirme.clear()
            edit.execute("CREATE TABLE IF NOT EXISTS ürünler(isim TEXT,barkod TEXT,fiyat NUMBER)")
            tablo.commit()
            edit.execute("INSERT INTO ürünler VALUES (?,?,?)", (isim, barkod, fiyat))
            tablo.commit()
            self.barkodgiris.clear()
            self.urunadigirs.clear()
            self.urunfiyatigiris.clear()

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow", "MainWindow"))
        self.satisyap.setText(_translate("SecondWindow", "ÜRÜN EKLE"))
        self.Telif.setText(_translate("SecondWindow", "© BU UYGULAMANIN BÜTÜN TELİF HAKLARI MAHMUT KUT\'A AİTTİR"))
        self.barkodbilgi.setText(_translate("SecondWindow", "ÜRÜN BARKODU OKUT :"))
        self.urunadibilgi.setText(_translate("SecondWindow", "ÜRÜNÜN ADINI GİRİN :"))
        self.urunfiyatibilgi.setText(_translate("SecondWindow", "ÜRÜNÜN  FİYATI GİRİNİZ :"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SecondWindow = QtWidgets.QMainWindow()
    ui = Ui_SecondWindow()
    ui.setupUi(SecondWindow)
    SecondWindow.show()
    sys.exit(app.exec_())

